"""initial schema"""

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingdefinition',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('building_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction_cost', sa.JSON(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('gameitem',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_type', sa.Enum('icon', 'illustration', name='itemvisualtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_days', sa.Integer(), nullable=False),
    sa.Column('construction_resources', sa.JSON(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('location',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('map_x', sa.Float(), nullable=False),
    sa.Column('map_y', sa.Float(), nullable=False),
    sa.Column('worker_days', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('nation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('last_population_growth_date', sa.Date(), nullable=True),
    sa.Column('population_growth_progress', sa.Integer(), nullable=False),
    sa.Column('consecutive_hunger_days', sa.Integer(), nullable=False),
    sa.Column('influence', sa.Integer(), nullable=False),
    sa.Column('housing_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('storage_coefficient', sa.Float(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('worktypedefinition',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intensity', sa.Enum('BASE', 'LIGHT', 'STANDARD', 'MEDIUM', 'HEAVY', name='workintensity'), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('dayreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('influence', sa.Integer(), nullable=False),
    sa.Column('food_shortage', sa.Float(), nullable=False),
    sa.Column('is_hungry', sa.Boolean(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('workers_summary', sa.JSON(), nullable=False),
    sa.Column('processes_summary', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nation_id', 'report_date')
    )
    op.create_index(op.f('ix_dayreport_nation_id'), 'dayreport', ['nation_id'], unique=False)
    op.create_table('locationbuildingdefinition',
    sa.Column('location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('building_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['building_code'], ['buildingdefinition.code'], ),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.PrimaryKeyConstraint('location_code', 'building_code')
    )
    op.create_table('locationneighbor',
    sa.Column('location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('neighbor_location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('neighbor_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['neighbor_location_code'], ['location.code'], ),
    sa.PrimaryKeyConstraint('location_code', 'neighbor_location_code')
    )
    op.create_table('locationworktype',
    sa.Column('location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_type_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['work_type_code'], ['worktypedefinition.code'], ),
    sa.PrimaryKeyConstraint('location_code', 'work_type_code')
    )
    op.create_table('nationbuilding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('building_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('built_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['building_code'], ['buildingdefinition.code'], ),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationbuilding_building_code'), 'nationbuilding', ['building_code'], unique=False)
    op.create_index(op.f('ix_nationbuilding_location_code'), 'nationbuilding', ['location_code'], unique=False)
    op.create_index(op.f('ix_nationbuilding_nation_id'), 'nationbuilding', ['nation_id'], unique=False)
    op.create_table('nationlocation',
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_discovered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.PrimaryKeyConstraint('nation_id', 'location_code')
    )
    op.create_table('nationlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationlog_nation_id'), 'nationlog', ['nation_id'], unique=False)
    op.create_table('nationresource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.ForeignKeyConstraint(['resource_code'], ['resource.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nation_id', 'resource_code')
    )
    op.create_index(op.f('ix_nationresource_nation_id'), 'nationresource', ['nation_id'], unique=False)
    op.create_index(op.f('ix_nationresource_resource_code'), 'nationresource', ['resource_code'], unique=False)
    op.create_table('personaltask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personaltask_nation_id'), 'personaltask', ['nation_id'], unique=False)
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nation_building_id', sa.Integer(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_workers', sa.Integer(), nullable=False),
    sa.Column('required_worker_days', sa.Integer(), nullable=True),
    sa.Column('completed_worker_days', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['nation_building_id'], ['nationbuilding.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.ForeignKeyConstraint(['work_type'], ['worktypedefinition.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_location_code'), 'process', ['location_code'], unique=False)
    op.create_index(op.f('ix_process_nation_building_id'), 'process', ['nation_building_id'], unique=False)
    op.create_index(op.f('ix_process_nation_id'), 'process', ['nation_id'], unique=False)
    op.create_index(op.f('ix_process_work_type'), 'process', ['work_type'], unique=False)
    op.create_table('nationitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('nation_building_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('game_item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('built_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['game_item_code'], ['gameitem.code'], ),
    sa.ForeignKeyConstraint(['nation_building_id'], ['nationbuilding.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nation.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationitem_game_item_code'), 'nationitem', ['game_item_code'], unique=False)
    op.create_index(op.f('ix_nationitem_nation_building_id'), 'nationitem', ['nation_building_id'], unique=False)
    op.create_index(op.f('ix_nationitem_nation_id'), 'nationitem', ['nation_id'], unique=False)
    op.create_index(op.f('ix_nationitem_process_id'), 'nationitem', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nationitem_process_id'), table_name='nationitem')
    op.drop_index(op.f('ix_nationitem_nation_id'), table_name='nationitem')
    op.drop_index(op.f('ix_nationitem_nation_building_id'), table_name='nationitem')
    op.drop_index(op.f('ix_nationitem_game_item_code'), table_name='nationitem')
    op.drop_table('nationitem')
    op.drop_index(op.f('ix_process_work_type'), table_name='process')
    op.drop_index(op.f('ix_process_nation_id'), table_name='process')
    op.drop_index(op.f('ix_process_nation_building_id'), table_name='process')
    op.drop_index(op.f('ix_process_location_code'), table_name='process')
    op.drop_table('process')
    op.drop_index(op.f('ix_personaltask_nation_id'), table_name='personaltask')
    op.drop_table('personaltask')
    op.drop_index(op.f('ix_nationresource_resource_code'), table_name='nationresource')
    op.drop_index(op.f('ix_nationresource_nation_id'), table_name='nationresource')
    op.drop_table('nationresource')
    op.drop_index(op.f('ix_nationlog_nation_id'), table_name='nationlog')
    op.drop_table('nationlog')
    op.drop_table('nationlocation')
    op.drop_index(op.f('ix_nationbuilding_nation_id'), table_name='nationbuilding')
    op.drop_index(op.f('ix_nationbuilding_location_code'), table_name='nationbuilding')
    op.drop_index(op.f('ix_nationbuilding_building_code'), table_name='nationbuilding')
    op.drop_table('nationbuilding')
    op.drop_table('locationworktype')
    op.drop_table('locationneighbor')
    op.drop_table('locationbuildingdefinition')
    op.drop_index(op.f('ix_dayreport_nation_id'), table_name='dayreport')
    op.drop_table('dayreport')
    op.drop_table('worktypedefinition')
    op.drop_table('resource')
    op.drop_table('nation')
    op.drop_table('location')
    op.drop_table('gameitem')
    op.drop_table('buildingdefinition')
    # ### end Alembic commands ###
