"""Global game-balance settings."""

BASE_FOOD_SPENDING = 1
ACTIVE_POPULATION_PERCENT = 80
POPULATION_GROWTH_REQUIRED_HEALTHY_DAYS = 5
POPULATION_GROWTH_PERCENT = 10
HUNGER_STAGE_ONE_DAYS = 3
GENERAL_POINT_RESOURCE_COST = 1


def active_population(population: int) -> int:
    return population * ACTIVE_POPULATION_PERCENT // 100
